apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
spec:
  rules:
  - host: prometheus.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
           serviceName: prometheus-service
           servicePort: 8080

