apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-endpointslices-viewer
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: ingress-nginx-endpointslices-viewer
  apiGroup: rbac.authorization.k8s.io

